apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  # These values are replaced on cluster creation by workflow
  imageRepo: harbor-cicd.taco-cat.xyz
  imageGroup: tks
  clusterName: cluster.local
  clusterEndpointHost: CHANGEME
  clusterEndpointPort: CHANGEME
  tksCpNode: CHNAGEME
  tksInfraNode: CHNAGEME
  tksUserNode: CHANGEME
  keycloakIssuerUri: CHANGEME
  keycloakClientId: CHANGEME
charts:
- name: cluster-api-byoh
  override:
    cluster:
      name: $(clusterName)
      kubernetesVersion: v1.25.11
    byoCluster:
      bundleLookupBaseRegistry: harbor.taco-cat.xyz/cluster_api_provider_bringyourownhost
      controlPlaneEndpoint:
        host: $(clusterEndpointHost)
        port: $(clusterEndpointPort)
    kubeadmControlPlane:
      selector:
        matchLabels:
          role: $(clusterName)-control-plane
      replicas: $(tksCpNode)
      clusterConfiguration:
        apiServer:
          extraArgs:
            oidc-client-id: $(keycloakClientId)
            oidc-issuer-url: $(keycloakIssuerUri)
    machineDeployment:
    - name: taco
      replicas: $(tksInfraNode)
      selector:
        matchLabels:
          role: $(clusterName)-tks
      labels:
        servicemesh: enabled
        taco-egress-gateway: enabled
        taco-ingress-gateway: enabled
        taco-lma: enabled
    - name: normal
      replicas: $(tksUserNode)
      selector:
        matchLabels:
          role: $(clusterName)-worker

- name: ingress-nginx
  override:
    controller:
      nodeSelector:
        taco-lma: enabled
      resources:
        requests:
          cpu: 2000m
          memory: 4Gi
      service:
        externalTrafficPolicy: Local
        type: NodePort
      config:
        enable-underscores-in-headers: "true"
        proxy-body-size: "10m"
      image:
        registry: harbor.taco-cat.xyz
        image: tks/controller
        digest: ""
      admissionWebhooks:
        patch:
          image:
            registry: harbor.taco-cat.xyz
            image: tks/kube-webhook-certgen
            digest: ""

- name: cluster-autoscaler
  override:
    discoveryNamespace: $(clusterName)
    discoveryClusterName: $(clusterName)
    image:
      repository: $(imageRepo)/$(imageGroup)/cluster-autoscaler
      tag: v1.25.2

- name: cluster-autoscaler-rbac
  override:
    deployMgmtRbacOnly:
      targetNamespace: $(clusterName)
    image:
      repository: $(imageRepo)/$(imageGroup)/cluster-autoscaler
      tag: v1.25.2

- name: tigera-operator
  override:
    tigeraOperator:
      image: $(imageGroup)/calico-operator
      registry: $(imageRepo)
    calicoctl:
      image: $(imageRepo)/$(imageGroup)/calico-ctl
    installation:
      registry: $(imageRepo)/
      imagePath: $(imageGroup)
      imagePrefix: calico-

- name: local-path-provisioner
  override:
    image:
      repository: $(imageRepo)/$(imageGroup)/local-path-provisioner

- name: metrics-server
  override:
    image:
      repository: $(imageRepo)/$(imageGroup)/metrics-server

- name: argo-rollouts
  override:
    controller:
      image:
        registry: $(imageRepo)
        repository: $(imageGroup)/argo-rollouts
        tag: v1.4.1

    dashboard:
      image:
        registry: $(imageRepo)
        repository: $(imageGroup)/kubectl-argo-rollouts
        tag: v1.4.1
